version: '3.3'

services:

  wallet:
    container_name: near-wallet-generator
    build:
      context: .
      dockerfile: docker/production/nginx/Dockerfile
    restart: always
    ports:
      - "8080:80"
