name: "Near wallet generator"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_KEY }}
          known_hosts: ${{ secrets.PRODUCTION_HOST }}
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Deploy
        run: make deploy
        env:
          HOST: ${{ secrets.PRODUCTION_HOST }}
          PORT: ${{ secrets.PRODUCTION_PORT }}
        if: ${{ github.ref == 'refs/heads/main' }}
